# Generated by Django 5.2 on 2025-05-07 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anuncio_id', models.PositiveIntegerField(help_text='ID do anúncio denunciado')),
                ('motivo', models.CharField(choices=[('fraude', 'Fraude ou golpe'), ('conteudo_inadequado', 'Conteúdo inadequado'), ('informacao_falsa', 'Informações falsas'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'db_table': 'denuncias_anuncios',
                'ordering': ['-data_envio'],
            },
        ),
    ]
