# Generated by Django 5.2 on 2025-05-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escambuz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categoria1',
        ),
    ]
