# Generated by Django 5.2 on 2025-07-09 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escambuz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('nao_lida', 'Não Lida'), ('lida', 'Lida'), ('arquivada', 'Arquivada')], default='nao_lida', max_length=20)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'mensagens_usuarios',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaIrregular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_da_denuncia', models.CharField(choices=[('preco_irregular', 'Preço Irregular'), ('produto_nao_existente', 'Produto Não Existente'), ('informacao_incorreta', 'Informação Incorreta'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('descricao', models.TextField(blank=True, default='Nenhuma descrição fornecida.', null=True)),
                ('data_denuncia', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvida', 'Resolvida'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_irregulares', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_irregulares', to='escambuz.oferta')),
            ],
            options={
                'verbose_name': 'Denúncia Irregular',
                'verbose_name_plural': 'Denúncias Irregulares',
            },
        ),
    ]
