# Generated by Django 5.2 on 2025-05-07 19:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escambuz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='DenunciaIrregular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_da_denuncia', models.CharField(choices=[('preco_irregular', 'Preço Irregular'), ('produto_nao_existente', 'Produto Não Existente'), ('informacao_incorreta', 'Informação Incorreta'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('descricao', models.TextField(blank=True, default='Nenhuma descrição fornecida.', null=True)),
                ('data_denuncia', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvida', 'Resolvida'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_irregulares', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_irregulares', to='escambuz.oferta')),
            ],
            options={
                'verbose_name': 'Denúncia Irregular',
                'verbose_name_plural': 'Denúncias Irregulares',
            },
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
    ]
