# Generated by Django 5.2 on 2025-06-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escambuz', '0002_alter_objeto_options_transacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objeto',
            options={'verbose_name': 'Objeto', 'verbose_name_plural': 'Objetos'},
        ),
    ]
