# Generated by Django 5.2 on 2025-07-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escambuz', '0002_delete_denunciairregular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='tipo',
            field=models.CharField(choices=[('venda', 'Venda'), ('doacao', 'Doação'), ('troca', 'Troca')], max_length=10),
        ),
    ]
