# Generated by Django 5.2 on 2025-07-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escambuz', '0003_alter_categoria_nome_alter_objeto_data_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='objetos/')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='escambuz.objeto')),
            ],
            options={
                'verbose_name': 'Foto do Objeto',
                'verbose_name_plural': 'Fotos dos Objetos',
            },
        ),
    ]
