# Generated by Django 5.2 on 2025-07-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escambuz', '0003_alter_objeto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='objetos_imgs/'),
        ),
    ]
