# Generated by Django 5.2 on 2025-07-16 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria do item', max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(help_text='Descrição detalhada da categoria', verbose_name='Descrição da Categoria')),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a categoria está ativa', verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do documento histórico', max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do documento histórico', verbose_name='Descrição')),
                ('tipo_documento', models.CharField(choices=[('certidao', 'Certidão'), ('ata', 'Ata'), ('carta', 'Carta'), ('decreto', 'Decreto'), ('lei', 'Lei'), ('fotografia', 'Fotografia'), ('mapa', 'Mapa'), ('jornal', 'Jornal'), ('revista', 'Revista'), ('livro', 'Livro'), ('outro', 'Outro')], max_length=15, verbose_name='Tipo de Documento')),
                ('autor', models.CharField(blank=True, help_text='Autor do documento histórico', max_length=255, verbose_name='Autor')),
                ('data_origem', models.DateField(blank=True, help_text='Data de criação do documento original', null=True, verbose_name='Data de Origem')),
                ('local_origem', models.CharField(blank=True, help_text='Local onde o documento foi criado', max_length=255, verbose_name='Local de Origem')),
                ('numero_paginas', models.PositiveIntegerField(blank=True, help_text='Quantidade de páginas do documento', null=True, verbose_name='Número de Páginas')),
                ('documento', models.FileField(help_text='Arquivo digitalizado do documento histórico', upload_to='documentos_historicos/', verbose_name='Arquivo')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, help_text='Data em que o documento foi adicionado ao acervo', verbose_name='Data de Adição')),
                ('categoria', models.ForeignKey(help_text='Categoria do documento histórico', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='muzeu.categoria', verbose_name='Categoria')),
                ('usuario_adicionado', models.ForeignKey(help_text='Usuário que adicionou o documento ao acervo', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_adicionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Adicionou')),
            ],
            options={
                'verbose_name': 'Documento Histórico',
                'verbose_name_plural': 'Documentos Históricos',
                'ordering': ['-data_origem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ItemAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do item do acervo', max_length=255, verbose_name='Nome do Item')),
                ('descricao', models.TextField(help_text='Descrição detalhada do item do acervo', verbose_name='Descrição')),
                ('origem', models.CharField(help_text='Origem ou procedência do item', max_length=255, verbose_name='Origem')),
                ('data_origem', models.DateField(blank=True, help_text='Data estimada de criação/origem do item', null=True, verbose_name='Data de Origem')),
                ('numero_registro', models.CharField(help_text='Número único de registro do item no acervo', max_length=50, unique=True, verbose_name='Número de Registro')),
                ('estado_conservacao', models.CharField(choices=[('excelente', 'Excelente'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('pessimo', 'Péssimo')], default='bom', max_length=15, verbose_name='Estado de Conservação')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('em_restauracao', 'Em Restauração'), ('emprestado', 'Emprestado'), ('inativo', 'Inativo')], default='ativo', max_length=20, verbose_name='Status')),
                ('localizacao_fisica', models.CharField(blank=True, help_text='Local físico onde o item está armazenado', max_length=100, verbose_name='Localização Física')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado do item (opcional)', max_digits=10, null=True, verbose_name='Valor Estimado')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, help_text='Data em que o item foi adicionado ao acervo', verbose_name='Data de Adição')),
                ('categoria', models.ForeignKey(help_text='Categoria do item do acervo', on_delete=django.db.models.deletion.PROTECT, related_name='itens_acervo', to='muzeu.categoria', verbose_name='Categoria')),
                ('usuario_adicionado', models.ForeignKey(help_text='Usuário que adicionou o item ao acervo', on_delete=django.db.models.deletion.PROTECT, related_name='itens_adicionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Adicionou')),
            ],
            options={
                'verbose_name': 'Item do Acervo',
                'verbose_name_plural': 'Itens do Acervo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemItemAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem do item do acervo', upload_to='imagens_acervo/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, help_text='Legenda ou descrição da imagem', max_length=255, verbose_name='Legenda')),
                ('eh_principal', models.BooleanField(default=False, help_text='Marcar como imagem principal do item', verbose_name='Imagem Principal')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('item_acervo', models.ForeignKey(help_text='Item do acervo relacionado à imagem', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='muzeu.itemacervo', verbose_name='Item do Acervo')),
            ],
            options={
                'verbose_name': 'Imagem do Item do Acervo',
                'verbose_name_plural': 'Imagens dos Itens do Acervo',
                'ordering': ['item_acervo__nome', '-eh_principal', 'data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do patrimônio histórico', max_length=255, verbose_name='Nome do Patrimônio')),
                ('descricao', models.TextField(help_text='Descrição detalhada do patrimônio', verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('imaterial', 'Imaterial'), ('arquitetonico', 'Arquitetônico'), ('paisagistico', 'Paisagístico'), ('arqueologico', 'Arqueológico')], max_length=15, verbose_name='Tipo de Patrimônio')),
                ('data_origem', models.DateField(blank=True, help_text='Data estimada de origem do patrimônio', null=True, verbose_name='Data de Origem')),
                ('localizacao', models.CharField(help_text='Localização geográfica do patrimônio', max_length=255, verbose_name='Localização')),
                ('coordenadas', models.CharField(blank=True, help_text='Coordenadas GPS (opcional)', max_length=50, verbose_name='Coordenadas GPS')),
                ('status', models.CharField(choices=[('preservado', 'Preservado'), ('em_risco', 'Em Risco'), ('restauracao', 'Em Restauração'), ('perdido', 'Perdido')], default='preservado', max_length=15, verbose_name='Status de Conservação')),
                ('importancia_historica', models.TextField(blank=True, help_text='Descrição da importância histórica do patrimônio', verbose_name='Importância Histórica')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, help_text='Data em que o patrimônio foi adicionado ao sistema', verbose_name='Data de Adição')),
                ('usuario_adicionado', models.ForeignKey(help_text='Usuário que adicionou o patrimônio ao sistema', on_delete=django.db.models.deletion.PROTECT, related_name='patrimonios_adicionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Adicionou')),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem do patrimônio', upload_to='imagens_patrimonio/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, help_text='Legenda ou descrição da imagem', max_length=255, verbose_name='Legenda')),
                ('eh_principal', models.BooleanField(default=False, help_text='Marcar como imagem principal do patrimônio', verbose_name='Imagem Principal')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('patrimonio', models.ForeignKey(help_text='Patrimônio relacionado à imagem', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='muzeu.patrimonio', verbose_name='Patrimônio')),
            ],
            options={
                'verbose_name': 'Imagem do Patrimônio',
                'verbose_name_plural': 'Imagens dos Patrimônios',
                'ordering': ['patrimonio__nome', '-eh_principal', 'data_upload'],
            },
        ),
    ]
