# Generated by Django 5.2 on 2025-05-21 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria do item', max_length=255, verbose_name='Nome da categoria')),
                ('descricao', models.TextField(help_text='Descrição da categoria do item', verbose_name='Descrição da categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do documento histórico', max_length=255, verbose_name='Título do documento')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do documento histórico', null=True, verbose_name='Descrição do documento')),
                ('autor', models.CharField(blank=True, help_text='Autor do documento histórico', max_length=255, null=True, verbose_name='Autor do documento')),
                ('data_origem', models.DateField(blank=True, help_text='Data de origem do documento histórico', null=True, verbose_name='Data de origem')),
                ('documento', models.FileField(help_text='Arquivo do documento histórico', upload_to='documentos_historicos/', verbose_name='Documento')),
                ('data_adicao', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data em que o documento foi adicionado ao acervo', null=True, verbose_name='Data de adição')),
                ('categoria', models.ForeignKey(help_text='Categoria do documento histórico', on_delete=django.db.models.deletion.PROTECT, to='muzeu.categoria', verbose_name='Categoria do documento')),
                ('usuario_adicionado', models.ForeignKey(help_text='Usuário que adicionou o documento ao acervo', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que adicionou')),
            ],
            options={
                'verbose_name': 'Documento Histórico',
                'verbose_name_plural': 'Documentos Históricos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ItemAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do item do acervo', max_length=255, verbose_name='Nome do item')),
                ('descricao', models.TextField(help_text='Descrição do item do acervo', verbose_name='Descrição do item')),
                ('origem', models.CharField(help_text='Origem do item do acervo', max_length=255, verbose_name='Origem do item')),
                ('data_adicao', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data em que o item foi adicionado ao acervo', null=True, verbose_name='Data de adição')),
                ('categoria', models.ForeignKey(help_text='Categoria do item do acervo', on_delete=django.db.models.deletion.PROTECT, to='muzeu.categoria', verbose_name='Categoria do item')),
                ('usuario_adicionado', models.ForeignKey(help_text='Usuário que adicionou o item ao acervo', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que adicionou')),
            ],
            options={
                'verbose_name': 'Item do Acervo',
                'verbose_name_plural': 'Itens do Acervo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemItemAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem do item do acervo', upload_to='imagens_acervo/', verbose_name='Imagem do item')),
                ('item_acervo', models.ForeignKey(help_text='Item do acervo relacionado à imagem', on_delete=django.db.models.deletion.PROTECT, to='muzeu.itemacervo', verbose_name='Item do acervo')),
            ],
            options={
                'verbose_name': 'Imagem do Item do Acervo',
                'verbose_name_plural': 'Imagens dos Itens do Acervo',
                'ordering': ['item_acervo__nome'],
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do patrimônio', max_length=255, verbose_name='Nome do patrimônio')),
                ('descricao', models.TextField(help_text='Descrição do patrimônio', verbose_name='Descrição do patrimônio')),
                ('data_origem', models.DateField(blank=True, help_text='Data de origem do patrimônio', null=True, verbose_name='Data de origem')),
                ('localizacao', models.CharField(help_text='Localização do patrimônio', max_length=255, verbose_name='Localização do patrimônio')),
                ('data_adicao', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data em que o patrimônio foi adicionado ao acervo', null=True, verbose_name='Data de adição')),
                ('usuario_adicionado', models.ForeignKey(help_text='Usuário que adicionou o patrimônio ao acervo', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que adicionou')),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem do patrimônio', upload_to='imagens_patrimonio/', verbose_name='Imagem do patrimônio')),
                ('patrimonio', models.ForeignKey(help_text='Patrimônio relacionado à imagem', on_delete=django.db.models.deletion.PROTECT, to='muzeu.patrimonio', verbose_name='Patrimônio')),
            ],
            options={
                'verbose_name': 'Imagem do Patrimônio',
                'verbose_name_plural': 'Imagens dos Patrimônios',
                'ordering': ['patrimonio__nome'],
            },
        ),
    ]
