# Generated by Django 4.2.7 on 2025-04-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GuiasTurismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do guia de turismo', max_length=100, verbose_name='Nome do Guia')),
                ('nome_tour', models.CharField(help_text='Nome do tour', max_length=150, verbose_name='Nome do Tour')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do guia de turismo', null=True, verbose_name='Descrição do Guia')),
                ('descricao_tour', models.TextField(blank=True, help_text='Descrição do tour', null=True, verbose_name='Descrição do Tour')),
                ('duracao', models.DurationField(blank=True, help_text='Duração do tour (hh:mm:ss)', null=True, verbose_name='Duração')),
                ('pontos_parada', models.TextField(blank=True, help_text='Lista dos pontos de parada do tour (um por linha)', null=True, verbose_name='Pontos de Parada')),
                ('nivel_dificuldade', models.CharField(blank=True, help_text='Nível de dificuldade do tour', max_length=50, null=True, verbose_name='Nível de Dificuldade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do tour', max_digits=10, null=True, verbose_name='Valor')),
                ('entidades_responsaveis', models.CharField(blank=True, help_text='Entidades responsáveis pelo tour', max_length=200, null=True, verbose_name='Entidades Responsáveis')),
            ],
            options={
                'verbose_name': 'Guia de Turismo',
                'verbose_name_plural': 'Guias de Turismo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do estabelecimento', max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, help_text='Endereço do estabelecimento', max_length=200, null=True, verbose_name='Endereço')),
                ('contato', models.CharField(blank=True, help_text='Telefone, e-mail ou outro contato', max_length=100, null=True, verbose_name='Contato')),
                ('horario_funcionamento', models.CharField(blank=True, help_text='Horário de funcionamento do estabelecimento', max_length=100, null=True, verbose_name='Horário de Funcionamento')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do estabelecimento', null=True, verbose_name='Descrição')),
                ('categoria', models.ForeignKey(help_text='Categoria do estabelecimento', on_delete=django.db.models.deletion.CASCADE, to='turismuz.categorias', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'ordering': ['nome'],
            },
        ),
    ]
