<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-07 16:44
=======
# Generated by Django 5.2 on 2025-05-21 17:01
>>>>>>> origin/develop

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota da avaliação (1 a 5)', verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, help_text='Comentário da avaliação', null=True, verbose_name='Comentário')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('usuario', models.CharField(help_text='Nome do usuário que avaliou', max_length=100, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GuiaTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do guia de turismo', max_length=100, verbose_name='Nome do Guia')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do guia de turismo', null=True, verbose_name='Descrição do Guia')),
                ('duracao', models.DurationField(blank=True, help_text='Duração do tour (hh:mm:ss)', null=True, verbose_name='Duração')),
                ('nivel_dificuldade', models.CharField(blank=True, help_text='Nível de dificuldade do tour', max_length=50, null=True, verbose_name='Nível de Dificuldade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do tour', max_digits=10, null=True, verbose_name='Valor')),
                ('entidade_responsavel', models.CharField(blank=True, help_text='Entidade responsável pelo tour', max_length=200, null=True, verbose_name='Entidade Responsável')),
<<<<<<< HEAD
=======
                ('imagem', models.ImageField(blank=True, help_text='Imagem do guia', null=True, upload_to='imagens_guias', verbose_name='Imagem')),
>>>>>>> origin/develop
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título que aparecerá no card de sua publicação.', max_length=255, verbose_name='Título da Publicação')),
                ('texto_da_noticia', models.TextField(help_text='Texto que aparecerá no corpo de sua publicação', verbose_name='Texto da Publicação')),
                ('data_de_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMIN', 'Admin'), ('AUTOR', 'Autor'), ('COMUM', 'Comum')], default='COMUM', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
=======
            name='Permissao',
>>>>>>> origin/develop
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMIN', 'Admin'), ('AUTOR', 'Autor'), ('COMUM', 'Comum')], default='COMUM', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título que aparecerá no card de sua publicação.', max_length=255, verbose_name='Título da Publicação')),
                ('texto_da_noticia', models.TextField(help_text='Texto que aparecerá no corpo de sua publicação', verbose_name='Texto da Publicação')),
                ('data_de_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem da publicação', null=True, upload_to='imagens_publicacoes', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EM_ANALISE', 'Em_analise'), ('RECUSADO', 'Recusado'), ('ACEITO', 'Aceito')], default='COMUM', max_length=10)),
                ('nome', models.CharField(help_text='Nome do estabelecimento', max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, help_text='Endereço do estabelecimento', max_length=200, null=True, verbose_name='Endereço')),
                ('contato', models.CharField(blank=True, help_text='Telefone, e-mail ou outro contato', max_length=100, null=True, verbose_name='Contato')),
                ('horario_funcionamento', models.CharField(blank=True, help_text='Horário de funcionamento do estabelecimento', max_length=100, null=True, verbose_name='Horário de Funcionamento')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do estabelecimento', null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem do estabelecimento', null=True, upload_to='imagens_estabelecimentos', verbose_name='Imagem')),
                ('categoria', models.ForeignKey(help_text='Categoria do estabelecimento', on_delete=django.db.models.deletion.CASCADE, to='turismuz.categorias', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_publicacoes', verbose_name='Fotos')),
                ('legenda', models.CharField(help_text='Descreva a imagem para funções de acessibilidade', max_length=255, verbose_name='Legenda da imagem')),
                ('noticia', models.ForeignKey(help_text='Publicação em que a imagem está vinculada', on_delete=django.db.models.deletion.PROTECT, to='turismuz.publicacao', verbose_name='Publicação da imagem')),
            ],
        ),
    ]
