# Generated by Django 5.2.4 on 2025-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='legenda_imagem',
            field=models.CharField(blank=True, help_text='Legenda da imagem principal', max_length=255, null=True, verbose_name='Legenda da Imagem'),
        ),
    ]
