# Generated by Django 4.2.7 on 2025-07-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ['-data_de_publicacao'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AddField(
            model_name='publicacao',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria da publicação', null=True, on_delete=django.db.models.deletion.SET_NULL, to='turismuz.categorias', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='legenda',
            field=models.CharField(blank=True, help_text='Legenda da imagem da publicação', max_length=255, null=True, verbose_name='Legenda da imagem'),
        ),
    ]
