# Generated by Django 4.2.7 on 2025-05-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do estabelecimento', null=True, upload_to='imagens_estabelecimentos', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='guiaturistico',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem do guia', null=True, upload_to='imagens_guias', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem da publicação', null=True, upload_to='imagens_publicacoes', verbose_name='Imagem'),
        ),
    ]
