# Generated by Django 4.2.7 on 2025-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(help_text='Nota da avaliação (1 a 5)', verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, help_text='Comentário da avaliação', null=True, verbose_name='Comentário')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('usuario', models.CharField(help_text='Nome do usuário que avaliou', max_length=100, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título que aparecerá no card de sua publicação.', max_length=255, verbose_name='Título da Publicação')),
                ('texto_da_noticia', models.TextField(help_text='Texto que aparecerá no corpo de sua publicação', verbose_name='Texto da Publicação')),
                ('data_de_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
            ],
        ),
    ]
