# Generated by Django 5.2 on 2025-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='estado',
            field=models.CharField(choices=[('EM_ANALISE', 'Em_analise'), ('RECUSADO', 'Recusado'), ('ACEITO', 'Aceito')], default='COMUM', max_length=10),
        ),
    ]
