# Generated by Django 5.2 on 2025-05-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0002_estabelecimento_estado'),
        ('turismuz', '0002_estabelecimento_imagem_guiaturistico_imagem_and_more'),
        ('turismuz', '0002_publicacao_estado'),
    ]

    operations = [
    ]
