# Generated by Django 4.2.7 on 2025-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0002_avaliacao_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(default=1, help_text='Imagem que aparecerá no card de sua publicação.', upload_to='imagens_publicacoes/', verbose_name='Imagem da Publicação'),
            preserve_default=False,
        ),
    ]
