# Generated by Django 5.2 on 2025-04-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0002_avaliacao_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_publicacoes', verbose_name='Fotos')),
                ('legenda', models.CharField(help_text='Descreva a imagem para funções de acessibilidade', max_length=255, verbose_name='Legenda da imagem')),
                ('noticia', models.ForeignKey(help_text='Publicação em que a imagem está vinculada', on_delete=django.db.models.deletion.PROTECT, to='turismuz.publicacao', verbose_name='Publicação da imagem')),
            ],
        ),
    ]
