# Generated by Django 4.2.7 on 2025-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0002_alter_publicacao_options_publicacao_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaturistico',
            name='contato',
            field=models.CharField(blank=True, help_text='Informações de contato do guia (telefone, email, etc.)', max_length=200, null=True, verbose_name='Contato do Guia'),
        ),
    ]
