# Generated by Django 5.2 on 2025-04-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0003_imagempublicacao'),
        ('turismuz', '0003_publicacao_imagem'),
    ]

    operations = [
    ]
