# Generated by Django 4.2.7 on 2025-07-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turismuz', '0003_guiaturistico_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria do estabelecimento', null=True, on_delete=django.db.models.deletion.CASCADE, to='turismuz.categorias', verbose_name='Categoria'),
        ),
    ]
