# Generated by Django 5.2 on 2025-05-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('historico', models.TextField(blank=True, null=True)),
                ('consentimento_lgpd', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('cirurgia', 'Cirurgia'), ('transporte', 'Transporte')], max_length=20)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em Análise'), ('agendado', 'Agendado'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsaude.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_agendada', models.DateTimeField()),
                ('local', models.CharField(max_length=150)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status_agendamento', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsaude.solicitacao')),
            ],
        ),
    ]
