# Generated by Django 5.2.1 on 2025-06-11 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doamuz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='contato',
            field=models.CharField(default=django.utils.timezone.now, help_text='Telefone', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
