# Generated by Django 5.2 on 2025-04-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doamuz', '0002_doacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_do_comentario', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
