# Generated by Django 5.2 on 2025-05-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doamuz', '0002_doacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
        migrations.DeleteModel(
            name='doacao',
        ),
    ]
