# Generated by Django 5.2 on 2025-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doamuz', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='avaliacao',
            field=models.BooleanField(default=False, verbose_name='Avaliação'),
        ),
    ]
