# Generated by Django 5.2 on 2025-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doamuz', '0004_feedback_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='avaliacao',
            field=models.IntegerField(choices=[(1, 'Positivo'), (2, 'Negativo')], default=2, verbose_name='Avaliação'),
        ),
    ]
