# Generated by Django 5.2 on 2025-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doamuz', '0005_alter_feedback_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='tipo_doação',
            field=models.TextField(default=1, help_text='Qual foi a categoria da doação?'),
            preserve_default=False,
        ),
    ]
