# Generated by Django 5.2 on 2025-04-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doamuz', '0007_cidade_remove_categoria_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_organizacao', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('contato', models.IntegerField()),
                ('horario_de_funcionamento', models.CharField(max_length=100, verbose_name='Horário de Funcionamento')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doamuz.categoria')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doamuz.cidade')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doamuz.estado')),
            ],
            options={
                'verbose_name': 'Ong',
                'verbose_name_plural': 'Ongs',
            },
        ),
    ]
