# Generated by Django 5.2 on 2025-04-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doamuz', '0008_ongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongs',
            name='horario_de_funcionamento',
            field=models.TimeField(),
        ),
    ]
