# Generated by Django 5.2 on 2025-06-17 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamemuz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuscaDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255, verbose_name='Termo de busca')),
                ('categoria', models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoria filtrada')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Status filtrado')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data inicial')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro filtrado')),
                ('data_busca', models.DateTimeField(auto_now_add=True, verbose_name='Momento da busca')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamemuz.denuncia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
