# Generated by Django 5.2.1 on 2025-06-11 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamemuz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id_midia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('url_arquivo', models.URLField(max_length=500)),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamemuz.denuncia')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamemuz.denuncia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
