# Generated by Django 5.2 on 2025-05-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cemitério')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade do cemitério')),
            ],
            options={
                'verbose_name': 'Cemitério',
                'verbose_name_plural': 'Cemitérios',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=3, verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='AreaCemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do área')),
                ('cemiterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.cemiterio')),
            ],
            options={
                'verbose_name': 'Área do cemitério',
                'verbose_name_plural': 'Áreas do cemitério',
            },
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=100, verbose_name='Horas de visitação')),
                ('diahora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.dia')),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Horas',
            },
        ),
        migrations.CreateModel(
            name='HorarioVisitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100, verbose_name='Horário de visitação')),
                ('cemiterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.cemiterio')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
            },
        ),
        migrations.AddField(
            model_name='dia',
            name='diahorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.horariovisitacao'),
        ),
        migrations.CreateModel(
            name='Tumulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, verbose_name='Número do túmulo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.areacemiterio')),
            ],
            options={
                'verbose_name': 'Túmulo',
                'verbose_name_plural': 'Túmulos',
            },
        ),
    ]
