# Generated by Django 5.2 on 2025-05-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cemitério')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade do cemitério')),
            ],
            options={
                'verbose_name': 'Cemitério',
                'verbose_name_plural': 'Cemitérios',
            },
        ),
    ]
