# Generated by Django 5.2 on 2025-07-16 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome oficial do cemitério', max_length=100, verbose_name='Nome do Cemitério')),
                ('cidade', models.CharField(help_text='Cidade onde o cemitério está localizado', max_length=100, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, help_text='Endereço completo do cemitério', max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Digite um número de telefone válido', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cemitério',
                'verbose_name_plural': 'Cemitérios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AreaCemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome ou identificação da área', max_length=100, verbose_name='Nome da Área')),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional da área', verbose_name='Descrição')),
                ('cemiterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='covamuz.cemiterio', verbose_name='Cemitério')),
            ],
            options={
                'verbose_name': 'Área do Cemitério',
                'verbose_name_plural': 'Áreas do Cemitério',
                'ordering': ['cemiterio__nome', 'nome'],
                'unique_together': {('nome', 'cemiterio')},
            },
        ),
        migrations.CreateModel(
            name='HorarioVisitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Descrição do período de visitação', max_length=100, verbose_name='Nome do Horário')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o horário está ativo', verbose_name='Ativo')),
                ('cemiterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_visitacao', to='covamuz.cemiterio', verbose_name='Cemitério')),
            ],
            options={
                'verbose_name': 'Horário de Visitação',
                'verbose_name_plural': 'Horários de Visitação',
                'ordering': ['cemiterio__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Tumulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número ou identificação do túmulo', max_length=50, verbose_name='Número do Túmulo')),
                ('tipo', models.CharField(blank=True, help_text='Tipo do túmulo (jazigo, gaveta, etc.)', max_length=50, verbose_name='Tipo de Túmulo')),
                ('ocupado', models.BooleanField(default=False, help_text='Indica se o túmulo está ocupado', verbose_name='Ocupado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tumulos', to='covamuz.areacemiterio', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Túmulo',
                'verbose_name_plural': 'Túmulos',
                'ordering': ['area__cemiterio__nome', 'area__nome', 'numero'],
                'unique_together': {('numero', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo da pessoa falecida', max_length=100, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('data_falecimento', models.DateField(verbose_name='Data de Falecimento')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais', verbose_name='Observações')),
                ('cemiterio', models.ForeignKey(help_text='Cemitério onde está enterrado(a)', on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='covamuz.cemiterio', verbose_name='Cemitério')),
                ('tumulo', models.ForeignKey(help_text='Túmulo onde está enterrado(a)', on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='covamuz.tumulo', verbose_name='Túmulo')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HoraDiaVisitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(help_text='Horário de início da visitação', verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(help_text='Horário de fim da visitação', verbose_name='Hora de Fim')),
                ('dia', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Dia da Semana')),
                ('horario_visitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_dias', to='covamuz.horariovisitacao', verbose_name='Horário de Visitação')),
            ],
            options={
                'verbose_name': 'Hora e Dia de Visitação',
                'verbose_name_plural': 'Horas e Dias de Visitação',
                'ordering': ['horario_visitacao', 'dia', 'hora_inicio'],
                'unique_together': {('dia', 'hora_inicio', 'horario_visitacao')},
            },
        ),
    ]
