# Generated by Django 5.2 on 2025-05-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covamuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('data_nasc', models.DateField(verbose_name='Data De Nascimento')),
                ('data_fale', models.DateField(verbose_name='Data De Falecimento')),
                ('cemiterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.cemiterio', verbose_name='Cemitério onde entá esterrado(a)')),
                ('tumulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.tumulo', verbose_name='Túmulo onde está enterrado')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
