# Generated by Django 5.2 on 2025-05-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covamuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do área')),
                ('Cemiterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covamuz.cemiterio')),
            ],
            options={
                'verbose_name': 'Área do cemitério',
                'verbose_name_plural': 'Áreas do cemitério',
            },
        ),
    ]
