# Generated by Django 5.2 on 2025-06-11 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covamuz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hora',
            name='diahora',
        ),
        migrations.CreateModel(
            name='DiaVisitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, verbose_name='Dia')),
                ('diahorario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.horariovisitacao')),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='HoraVisitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=100, verbose_name='Horas de visitação')),
                ('diahora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.diavisitacao')),
            ],
            options={
                'verbose_name': 'Hora',
                'verbose_name_plural': 'Horas',
            },
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='Hora',
        ),
    ]
