# Generated by Django 5.2 on 2025-05-07 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covamuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do área')),
                ('cemiterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.cemiterio')),
            ],
            options={
                'verbose_name': 'Área do cemitério',
                'verbose_name_plural': 'Áreas do cemitério',
            },
        ),
        migrations.CreateModel(
            name='Tumulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, verbose_name='Número do túmulo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covamuz.areacemiterio')),
            ],
            options={
                'verbose_name': 'Túmulo',
                'verbose_name_plural': 'Túmulos',
            },
        ),
    ]
