# Generated by Django 5.2 on 2025-07-23 23:16

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.core.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
