# Generated by Django 5.2 on 2025-05-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
                'db_table': 'combustivel',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do local')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'db_table': 'local',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cnh_numero', models.CharField(max_length=20, unique=True, verbose_name='Número da CNH')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículos',
                'db_table': 'tipo_veiculo',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de fabricação')),
                ('foto', models.ImageField(upload_to='veiculos/', verbose_name='Foto')),
                ('capacidade', models.PositiveIntegerField(blank=True, help_text='Número de passageiros ou capacidade de carga', null=True, verbose_name='Capacidade')),
                ('condicao_manutencao', models.CharField(choices=[('bom', 'Bom'), ('regular', 'Regular'), ('manutencao', 'Em manutenção'), ('inativo', 'Inativo')], default='bom', max_length=50, verbose_name='Condição de manutenção')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='movemuz.combustivel', verbose_name='Combustível')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='movemuz.tipoveiculo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculo',
            },
        ),
        migrations.CreateModel(
            name='HorarioTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_partida', models.TimeField(verbose_name='Horário de partida')),
                ('dias_semana', models.CharField(help_text='Ex: Segunda a sexta, Fins de semana, Todos os dias', max_length=100, verbose_name='Dias da semana')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_destino', to='movemuz.local', verbose_name='Destino')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_origem', to='movemuz.local', verbose_name='Origem')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movemuz.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Horário de Transporte',
                'verbose_name_plural': 'Horários de Transporte',
                'db_table': 'horario_transporte',
                'ordering': ['-horario_partida'],
            },
        ),
        migrations.CreateModel(
            name='EscalaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_saida', models.DateTimeField(verbose_name='Horário de saída')),
                ('horario_chegada', models.DateTimeField(verbose_name='Horário de chegada previsto')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas_destino', to='movemuz.local', verbose_name='Destino')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas_origem', to='movemuz.local', verbose_name='Origem')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='movemuz.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Escala do Veículo',
                'verbose_name_plural': 'Escalas dos Veículos',
                'db_table': 'escala_veiculo',
                'ordering': ['-horario_saida'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(verbose_name='Data e hora de saída')),
                ('data_chegada', models.DateTimeField(blank=True, null=True, verbose_name='Previsão de chegada')),
                ('finalidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Finalidade da viagem')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_destino', to='movemuz.local', verbose_name='Destino')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movemuz.motorista', verbose_name='motorista')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_origem', to='movemuz.local', verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-data_saida'],
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do passageiro')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento de identificação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='movemuz.viagem')),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
                'db_table': 'passageiro',
            },
        ),
    ]
