<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-30 17:19

=======
# Generated by Django 5.2 on 2025-04-30 17:02

import django.db.models.deletion
>>>>>>> d7ec35e (Adcionando models e admin)
=======
# Generated by Django 5.2 on 2025-05-07 16:35
=======
# Generated by Django 5.2 on 2025-05-07 16:44
>>>>>>> 2b295a9 ([Refactor] Resetar todas as migrações (#219))

import django.db.models.deletion
>>>>>>> f40509e ([Fix] Corrigir problemas na aplicação MoveMuz (#217))
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
=======
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
                'db_table': 'combustivel',
            },
        ),
        migrations.CreateModel(
>>>>>>> f40509e ([Fix] Corrigir problemas na aplicação MoveMuz (#217))
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cnh_numero', models.CharField(max_length=20, unique=True, verbose_name='Número da CNH')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
<<<<<<< HEAD
=======
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
=======
>>>>>>> f40509e ([Fix] Corrigir problemas na aplicação MoveMuz (#217))
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
<<<<<<< HEAD
=======
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículos',
                'db_table': 'tipo_veiculo',
            },
>>>>>>> f40509e ([Fix] Corrigir problemas na aplicação MoveMuz (#217))
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('cor', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('foto', models.ImageField(upload_to='veiculos/')),
<<<<<<< HEAD
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combustivel', to='movemuz.combustivel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='movemuz.tipoveiculo')),
            ],
>>>>>>> d7ec35e (Adcionando models e admin)
=======
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='movemuz.combustivel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='movemuz.tipoveiculo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculo',
            },
>>>>>>> f40509e ([Fix] Corrigir problemas na aplicação MoveMuz (#217))
        ),
    ]
