# Generated by Django 5.2 on 2025-04-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movemuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combustivel',
            options={'verbose_name': 'Combustível', 'verbose_name_plural': 'Combustíveis'},
        ),
        migrations.AlterModelOptions(
            name='tipoveiculo',
            options={'verbose_name': 'Tipo de Veículo', 'verbose_name_plural': 'Tipos de Veículos'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='movemuz.combustivel'),
        ),
        migrations.AlterModelTable(
            name='combustivel',
            table='combustivel',
        ),
        migrations.AlterModelTable(
            name='tipoveiculo',
            table='tipo_veiculo',
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculo',
        ),
    ]
