# Generated by Django 5.2 on 2025-05-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movemuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupacaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da viagem')),
                ('passageiros_a_bordo', models.PositiveIntegerField(verbose_name='Passageiros a bordo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('horario_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupacoes', to='movemuz.horariotransporte', verbose_name='Horário de Transporte')),
            ],
            options={
                'verbose_name': 'Ocupação do Veículo',
                'verbose_name_plural': 'Ocupações dos Veículos',
                'db_table': 'ocupacao_veiculo',
                'ordering': ['-data', '-atualizado_em'],
                'unique_together': {('horario_transporte', 'data')},
            },
        ),
    ]
