# Generated by Django 5.2 on 2025-04-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movemuz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do local')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(verbose_name='Data e hora de saída')),
                ('data_chegada', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de chegada')),
                ('finalidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Finalidade da viagem')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_destino', to='movemuz.local', verbose_name='Destino')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movemuz.motorista', verbose_name='Motorista')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_origem', to='movemuz.local', verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-data_saida'],
            },
        ),
    ]
