# Generated by Django 5.2 on 2025-05-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movemuz', '0002_local_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='data_chegada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de chegada'),
        ),
    ]
