# Generated by Django 5.2 on 2025-05-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movemuz', '0003_alter_viagem_data_chegada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movemuz.motorista', verbose_name='motorista'),
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do passageiro')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento de identificação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='movemuz.viagem')),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
                'db_table': 'passageiro',
            },
        ),
    ]
