# Generated by Django 5.2 on 2025-07-23 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do campeonato')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('tipo', models.CharField(choices=[('pontos_corridos', 'Pontos Corridos'), ('grupos_mata_mata', 'Grupos + Mata-mata')], default='pontos_corridos', max_length=20)),
                ('data_inicio', models.DateField(blank=True, help_text='Data prevista de início', null=True)),
                ('data_fim_prevista', models.DateField(blank=True, help_text='Data prevista de término', null=True)),
                ('local_padrao', models.CharField(blank=True, help_text='Local padrão para as partidas', max_length=200)),
                ('numero_grupos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('times_por_grupo', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)])),
                ('classificados_por_grupo', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fase_inicial_mata_mata', models.CharField(choices=[('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semifinal', 'Semifinal'), ('final', 'Final')], default='quartas', help_text='A partir de qual fase começará o mata-mata', max_length=20)),
                ('max_equipes', models.IntegerField(blank=True, help_text='Número máximo de equipes (deixe em branco para ilimitado)', null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('classificacao_inicial', models.CharField(choices=[('alfabetica', 'Ordem Alfabética'), ('aleatoria', 'Ordem Aleatória'), ('manual', 'Definição Manual'), ('ranking', 'Por Ranking/Histórico')], default='alfabetica', max_length=20)),
                ('permite_empate', models.BooleanField(default=True, help_text='Se permite empates nas partidas')),
                ('tipo_geracao_rodada', models.CharField(choices=[('manual', 'Manual - Organizador define'), ('automatica', 'Automática - Sistema distribui'), ('hibrida', 'Híbrida - Mista')], default='manual', max_length=20)),
                ('partidas_por_rodada', models.IntegerField(default=1, help_text='Quantas partidas por rodada (para geração automática)', validators=[django.core.validators.MinValueValidator(1)])),
                ('dias_entre_rodadas', models.IntegerField(default=7, help_text='Intervalo em dias entre rodadas', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('inscricoes_abertas', 'Inscrições Abertas'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-ano', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('cidade', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('tipo_rodada', models.CharField(choices=[('fase_grupos', 'Fase de Grupos'), ('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('terceiro_lugar', 'Disputa de 3º Lugar'), ('pontos_corridos', 'Pontos Corridos')], default='pontos_corridos', max_length=20)),
                ('data_inicio', models.DateField(blank=True, help_text='Data de início da rodada', null=True)),
                ('data_fim', models.DateField(blank=True, help_text='Data de fim da rodada', null=True)),
                ('local_padrao', models.CharField(blank=True, help_text='Local padrão para todas as partidas desta rodada', max_length=200)),
                ('grupo', models.CharField(blank=True, help_text='Grupo específico desta rodada (se aplicável)', max_length=1, null=True)),
                ('partidas_simultaneas', models.BooleanField(default=True, help_text='Se todas as partidas devem ocorrer no mesmo dia')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a rodada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esportemuz.campeonato')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
                'ordering': ['campeonato', 'numero'],
                'unique_together': {('campeonato', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, max_length=200)),
                ('data_hora', models.DateTimeField(blank=True, help_text='Data e horário da partida', null=True)),
                ('duracao_prevista', models.IntegerField(default=90, help_text='Duração em minutos', validators=[django.core.validators.MinValueValidator(30)])),
                ('gols_mandante', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gols_visitante', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('penaltis_mandante', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('penaltis_visitante', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('adiada', 'Adiada'), ('cancelada', 'Cancelada'), ('w_o', 'W.O. (Walkover)')], default='agendada', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a partida')),
                ('arbitro', models.CharField(blank=True, help_text='Nome do árbitro', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('resultado_registrado_em', models.DateTimeField(blank=True, null=True)),
                ('equipe_mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_mandante', to='esportemuz.equipe')),
                ('equipe_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='esportemuz.equipe')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esportemuz.rodada')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['rodada__numero', 'data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=1, null=True)),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('gols_pro', models.IntegerField(default=0)),
                ('gols_contra', models.IntegerField(default=0)),
                ('saldo_gols', models.IntegerField(default=0)),
                ('pontos', models.IntegerField(default=0)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esportemuz.campeonato')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esportemuz.equipe')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['-pontos', '-saldo_gols', '-gols_pro', 'equipe__nome'],
                'unique_together': {('campeonato', 'equipe')},
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H')], max_length=1, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esportemuz.campeonato')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esportemuz.equipe')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'unique_together': {('campeonato', 'equipe')},
            },
        ),
    ]
