# Generated by Django 5.2 on 2025-04-30 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='StatusPartida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status da Partida',
                'verbose_name_plural': 'Status das Partidas',
            },
        ),
        migrations.CreateModel(
            name='TipoCampeonato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Campeonato',
                'verbose_name_plural': 'Tipos de Campeonato',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='esportemuz.campeonato', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='esportemuz.campeonato', verbose_name='Campeonato')),
                ('equipes', models.ManyToManyField(blank=True, related_name='grupos', to='esportemuz.equipe', verbose_name='Equipes')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.AddField(
            model_name='campeonato',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esportemuz.modalidade', verbose_name='Modalidade'),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('gols_mandante', models.PositiveIntegerField(default=0, verbose_name='Gols Mandante')),
                ('gols_visitante', models.PositiveIntegerField(default=0, verbose_name='Gols Visitante')),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='esportemuz.campeonato', verbose_name='Campeonato')),
                ('equipe_mandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_mandante', to='esportemuz.equipe', verbose_name='Equipe Mandante')),
                ('equipe_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_visitante', to='esportemuz.equipe', verbose_name='Equipe Visitante')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='esportemuz.grupo', verbose_name='Grupo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='esportemuz.statuspartida', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.AddField(
            model_name='campeonato',
            name='tipo_campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esportemuz.tipocampeonato', verbose_name='Tipo de Campeonato'),
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0, verbose_name='Pontos')),
                ('vitorias', models.PositiveIntegerField(default=0, verbose_name='Vitórias')),
                ('empates', models.PositiveIntegerField(default=0, verbose_name='Empates')),
                ('derrotas', models.PositiveIntegerField(default=0, verbose_name='Derrotas')),
                ('gols_pro', models.PositiveIntegerField(default=0, verbose_name='Gols Pró')),
                ('gols_contra', models.PositiveIntegerField(default=0, verbose_name='Gols Contra')),
                ('saldo_gols', models.IntegerField(default=0, verbose_name='Saldo de Gols')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='esportemuz.campeonato', verbose_name='Campeonato')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classificacoes', to='esportemuz.equipe', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['-pontos', '-vitorias', '-saldo_gols', '-gols_pro'],
                'unique_together': {('campeonato', 'equipe')},
            },
        ),
    ]
