# Generated by Django 5.2 on 2025-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora'),
        ),
    ]
