# Generated by Django 5.2 on 2025-05-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0002_alter_campeonato_id_alter_classificacao_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='campeonato',
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipes',
            field=models.ManyToManyField(blank=True, to='esportemuz.equipe', verbose_name='Equipes'),
        ),
    ]
