# Generated by Django 5.2 on 2025-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0002_alter_partida_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='encerrado',
            field=models.BooleanField(default=False, verbose_name='Encerrado'),
        ),
    ]
