# Generated by Django 5.2 on 2025-05-08 01:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0003_remove_equipe_campeonato_campeonato_equipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Local da Partida',
                'verbose_name_plural': 'Locais das Partidas',
            },
        ),
        migrations.RemoveField(
            model_name='partida',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
