# Generated by Django 5.2 on 2025-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0003_campeonato_encerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='partidas_jogadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Partidas Jogadas'),
        ),
    ]
