# Generated by Django 5.2 on 2025-05-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0004_local_remove_partida_grupo_delete_grupo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Local',
            new_name='LocalPartida',
        ),
    ]
