# Generated by Django 5.2 on 2025-05-08 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0005_rename_local_localpartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='esportemuz.localpartida', verbose_name='Local'),
        ),
    ]
