# Generated by Django 5.2 on 2025-05-14 11:21

import esportemuz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0006_alter_partida_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to=esportemuz.models.Equipe.get_path_escudo, verbose_name='Escudo'),
        ),
    ]
