# Generated by Django 5.2 on 2025-05-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportemuz', '0007_equipe_escudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='status',
        ),
        migrations.AddField(
            model_name='partida',
            name='encerrada',
            field=models.BooleanField(default=False, verbose_name='Encerrada'),
        ),
        migrations.DeleteModel(
            name='StatusPartida',
        ),
    ]
