# Generated by Django 5.2 on 2025-05-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('organizador', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('contato', models.CharField(max_length=100)),
                ('aprovado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventuz.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Vídeo')], max_length=5)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='midias_eventos/')),
                ('url_video', models.URLField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='eventuz.evento')),
            ],
        ),
    ]
