# Generated by Django 5.2 on 2025-05-07 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(help_text='Nome ou apelido do animal.', max_length=100, verbose_name='Nome do Animal')),
                ('descricao', models.TextField(help_text='Informações sobre o animal, comportamento, cuidados, etc.', verbose_name='Descrição')),
                ('foto', models.ImageField(help_text='Imagem do animal disponível para adoção.', upload_to='adocoes/fotos/', verbose_name='Foto do Animal')),
                ('contato', models.CharField(help_text='Número para contato com quem está doando.', max_length=20, validators=[django.core.validators.RegexValidator(message='Digite um número de telefone válido.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone ou WhatsApp')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('disponivel', models.BooleanField(default=True, help_text='Marque como falso quando o animal for adotado.', verbose_name='Disponível para Adoção')),
            ],
            options={
                'verbose_name': 'Anúncio de Adoção',
                'verbose_name_plural': 'Anúncios de Adoção',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome ou apelido do animal (se houver)', max_length=100, verbose_name='Nome do animal')),
                ('porte', models.CharField(help_text='Porte físico do animal (pequeno, médio, grande)', max_length=15, verbose_name='Porte')),
                ('raca', models.CharField(blank=True, help_text='Raça do animal (opcional).', max_length=50, null=True, verbose_name='Raça')),
                ('cor', models.CharField(help_text='Cor predominante do animal', max_length=30, verbose_name='Cor')),
                ('localizacao', models.CharField(help_text='Local onde o animal se encontra.', max_length=150, verbose_name='Localização')),
                ('foto', models.ImageField(help_text='Foto principal do animal', upload_to='animais/fotos', verbose_name='Foto do Animal')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do animal', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['nome'],
            },
        ),
    ]
