# Generated by Django 5.2 on 2025-04-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratamuz', '0002_usuario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='contratamuz.usuario')),
                ('serviço', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='contratamuz.servico')),
            ],
        ),
    ]
