# Generated by Django 5.2 on 2025-05-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratamuz', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
