# Generated by Django 5.2 on 2025-05-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratamuz', '0003_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='candidatura',
            options={'verbose_name': 'Candidatura', 'verbose_name_plural': 'Candidaturas'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='vagaemprego',
            options={'verbose_name': 'Vaga de Emprego', 'verbose_name_plural': 'Vagas de Emprego'},
        ),
        migrations.AddField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
