# Generated by Django 5.2 on 2025-07-23 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratamuz', '0004_add_telefone_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='telefone_contato',
        ),
    ]
