# Generated by Django 5.2 on 2025-05-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratamuz', '0004_alter_avaliacao_options_alter_candidatura_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='link_contato',
        ),
        migrations.AddField(
            model_name='servico',
            name='contato',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
