# Generated by Django 5.2 on 2025-07-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratamuz', '0005_remove_servico_telefone_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagaemprego',
            name='categoria',
            field=models.CharField(choices=[('musica', 'Música'), ('audio', 'Áudio e Produção'), ('eventos', 'Eventos'), ('marketing', 'Marketing Musical'), ('ensino', 'Ensino Musical'), ('instrumentos', 'Instrumentos'), ('tecnologia', 'Tecnologia Musical'), ('administracao', 'Administração'), ('vendas', 'Vendas'), ('outros', 'Outros')], default='outros', max_length=50),
        ),
    ]
